### ISSUE TITLE
Error in Image Build

### ISSUE THREAD

**Issue by MatteoGheza** [EvilFreelancer/docker-lfs-build#1]
I checked error: kernel not exist!!
$LFS/boot is empty.
Please check lfs build code. Thanks #

**Comment by MatteoGheza** [comment]
@EvilFreelancer Please check your code

**Comment by EvilFreelancer** [comment]
Hello! Thank you for your report, I'll check it

**Comment by MatteoGheza** [comment]
Thank you

**Comment by EvilFreelancer** [comment]
Somewhere is exit or some other killer of book.sh script, I recommend to use step by step solution:
1) Login to build container
2) Then instread of /book/book.sh run scripts from book.sh
```bash
# prepare to build
/book/chapter-3.sh

# Login as root
sudo su

#  change ownership
chown -R root:root $LFS/tools

# prevent "bad interpreter: Text file busy"
sync

# continue
/book/chapter-5.sh
/book/chapter-6.sh
/book/chapter-7.sh
/book/chapter-8.sh
/book/chapter-9.sh

# create dist
/image/image.sh
```

**Comment by MatteoGheza** [comment]
Ok thanks

**Comment by MatteoGheza** [comment]
Not work

**Comment by MatteoGheza** [comment]
I try to manual run each book file

**Comment by MatteoGheza** [comment]
It stop after sync

**Comment by MatteoGheza** [comment]
READ https://pastebin.com/ug3Npi1i

**Comment by EvilFreelancer** [comment]
> READ https://pastebin.com/ug3Npi1i

Yep, it's okay, just notice messages, you may go to the next step, at the end will be image.sh step, this should build few different images.

**Comment by MatteoGheza** [comment]
Ok

**Comment by MatteoGheza** [comment]
The bug is chroot

**Comment by MatteoGheza** [comment]
In chapter-n.sh

**Comment by MatteoGheza** [comment]
I need to manual run /tools/bin/env ecc. and bash --login ecc.

**Comment by MatteoGheza** [comment]
@MatteoGheza for chapter 6, 7, 8 and 9

**Comment by EvilFreelancer** [comment]
Hi! Can you solve it and suggest Pull Request?

**Comment by MatteoGheza** [comment]
I try
