### ISSUE TITLE
build success, but how to boot from iso

### ISSUE THREAD

**Issue by neatlife** [EvilFreelancer/docker-lfs-build#2]
![image](https://user-images.githubusercontent.com/4076198/73536376-ba37f500-4460-11ea-8a29-4fd2aa401d83.png)

**Comment by neatlife** [comment]
direct boot via vmware will cause this error:

![image](https://user-images.githubusercontent.com/4076198/73536463-e9e6fd00-4460-11ea-9c6a-e2d402d878ea.png)

**Comment by neatlife** [comment]
use lfs.iso

**Comment by EvilFreelancer** [comment]
Hello! It should work, probably was some error on build stage, I guess the Linux kernel was not build, did you has logs of build stage? By the way, you may try ISO from releases https://github.com/EvilFreelancer/docker-lfs-build/releases
